import { Analytics } from "@vercel/analytics/react"
import type { Metadata } from "next";
import { Suspense } from 'react';

import '../styles/destyle.css';
import '../styles/globals.css';
import { Noto_Sans_JP, Viaoda_Libre } from "next/font/google";

import Lenis from '@/components/features/Lenis';
import Footer from '@/components/layouts/Footer';

const NotoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  variable: '--font-noto-sans-jp',
});

const ViaodaLibre = Viaoda_Libre({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-viaoda_libre',
});

export const metadata: Metadata = {
  title: "Masashi Otsuka Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body className={`${NotoSansJP.variable} ${ViaodaLibre.variable}`}>
        <Suspense>
          <Lenis />
          {children}
          <Footer />
        </Suspense>
        <Analytics />
      </body>
    </html>
  );
}